In [15]:
import pandas as pd

In [18]:
cd = pd.read_csv("olist_customers_dataset.csv") 
gd=pd.read_csv("olist_geolocation_dataset.csv")
od=pd.read_csv("olist_orders_dataset.csv")
pyd=pd.read_csv("olist_order_payments_dataset.csv")
ord=pd.read_csv("olist_order_reviews_dataset.csv")
odd=pd.read_csv("olist_order_dataset.csv")
prd=pd.read_csv("olist_products_dataset.csv")

In [19]:
cd_clean= cd.copy()
gd_clean=gd.copy()
od_clean=od.copy()
pyd_clean=pyd.copy()
ord_clean=ord.copy()
prd_clean=prd.copy()

### data cleaning

In [21]:
cd_clean.shape
gd_clean.shape
od_clean.shape
pyd_clean.shape
ord_clean.shape
prd_clean.shape

(32951, 9)

In [22]:
cd_clean.dtypes
gd_clean.dtypes
od_clean.dtypes
pyd_clean.dtypes
ord_clean.dtypes
prd_clean.dtypes

product_id                     object
product_category_name          object
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

## Check Missing Values

### Customer dataset

In [23]:
#total mising values in each column
cd_clean.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [24]:
#total missing values in the entire dataset
print(cd_clean.isnull().sum().sum())

0

In [8]:
#percentage of missing values in each column
print((cd.isnull().sum()/len(cd)) * 100)

customer_id                 0.0
customer_unique_id          0.0
customer_zip_code_prefix    0.0
customer_city               0.0
customer_state              0.0
dtype: float64

### Geolocation dataset

In [25]:

gd_clean.isnull().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [26]:
print(gd_clean.isnull().sum().sum())

0

In [27]:
print(gd_clean.duplicated().sum())

261831

In [28]:
gd_clean[gd_clean.duplicated()]

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
15,1046,-23.546081,-46.644820,sao paulo,SP
44,1046,-23.546081,-46.644820,sao paulo,SP
65,1046,-23.546081,-46.644820,sao paulo,SP
66,1009,-23.546935,-46.636588,sao paulo,SP
67,1046,-23.546081,-46.644820,sao paulo,SP
...,...,...,...,...,...
1000153,99970,-28.343273,-51.873734,ciriaco,RS
1000154,99950,-28.070493,-52.011342,tapejara,RS
1000159,99900,-27.877125,-52.224882,getulio vargas,RS
1000160,99950,-28.071855,-52.014716,tapejara,RS
1000162,99950,-28.070104,-52.018658,tapejara,RS

In [31]:
gd_clean.drop_duplicates(inplace=True)

### order_items

In [37]:
od_clean.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [40]:
print(od_clean.isnull().sum().sum())

4908

In [45]:
print(od_clean.isnull().sum()/len(od_clean) * 100)

order_id                         0.000000
customer_id                      0.000000
order_status                     0.000000
order_purchase_timestamp         0.000000
order_approved_at                0.160899
order_delivered_carrier_date     1.793023
order_delivered_customer_date    2.981668
order_estimated_delivery_date    0.000000
dtype: float64

In [49]:
od_clean[od_clean.isnull()]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
99436,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99437,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99438,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99439,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99440,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
od_clean.dropna(inplace=True)

In [59]:
print(od_clean.duplicated().sum())

0

### Order payments

In [66]:
pyd_clean.isnull().sum().sum()

np.int64(0)

In [69]:
print(pyd_clean.isnull().sum().sum())

0

In [72]:
print(pyd_clean.duplicated().sum())

0

### order reviews dataset

In [75]:
ord_clean.isnull().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [78]:
ord_clean.isnull().sum()/len(ord_clean) * 100

review_id                   0.000000
order_id                    0.000000
review_score                0.000000
review_comment_title       88.341530
review_comment_message     58.702532
review_creation_date        0.000000
review_answer_timestamp     0.000000
dtype: float64

In [93]:
ord_clean.shape

(99224, 7)

In [94]:
ord_clean.dropna(inplace=True)

In [82]:
print(ord_clean.duplicated().sum())

0

In [95]:
ord_clean.shape

(9839, 7)

### order dataset

145903